/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_ttyz_tourfrxohc_jni_JNITools */

#ifndef _Included_xyz_ttyz_tourfrxohc_jni_JNITools
#define _Included_xyz_ttyz_tourfrxohc_jni_JNITools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_ttyz_tourfrxohc_jni_JNITools
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xyz_ttyz_tourfrxohc_jni_JNITools_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
